services:
  chat-service:
    build: .
    image: chat-service:latest
    container_name: chat-service
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGODB_URI=mongodb://shared-mongodb:27017/chat_service
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=${RABBITMQ_URL}
    volumes:
      - ./logs:/usr/src/app/logs
      - ./uploads:/usr/src/app/uploads
    networks:
      - chat-network
      - shared-infrastructure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  chat-network:
    driver: bridge
  shared-infrastructure:
    external: true
    name: shared-infrastructure